import * as esbuild from 'esbuild';
import * as babel from '@babel/core';
import * as React from 'react';
import * as PIXI from 'pixi.js';

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

// =========================================
//     rename styles generated by Vite
// =========================================

await fs.promises.rename(
  path.resolve(__dirname, '../dist/style.css'),
  path.resolve(__dirname, '../dist/hglib.css'),
);

// =========================================
//  prod (un)minified UMD (hglib/hglib.min)
// =========================================

// we transform the contents of the vite build
const viteUmdOutput = path.resolve(__dirname, '../dist/higlass.umd.js');

const transpiled = await babel.transformFileAsync(viteUmdOutput, {
  plugins: ['@babel/plugin-transform-classes'],
});

const unminifed = await esbuild.transform(transpiled.code, {
  minify: false,
  define: {
    'process.env.NODE_ENV': `"production"`,
  },
});

await fs.promises.writeFile(
  path.resolve(__dirname, '../dist/hglib.js'),
  unminifed.code,
);

const minifed = await esbuild.transform(transpiled.code, {
  minify: true,
  define: {
    'process.env.NODE_ENV': `"production"`,
  },
});

await fs.promises.writeFile(
  path.resolve(__dirname, '../dist/hglib.min.js'),
  minifed.code,
);

// delete the vite now that we have the final UMDs
await fs.promises.unlink(viteUmdOutput);

// =========================================
//       UMD demo (dist/index.html)
// =========================================

const esmHTML = await fs.promises.readFile(
  path.resolve(__dirname, '../index.html'),
  { encoding: 'utf-8' },
);

const base = 'https://unpkg.com';
const reactVersion = React.version.split('.')[0];
const pixiVersion = PIXI.VERSION.split('.')[0];

await fs.promises.writeFile(
  path.resolve(__dirname, '../dist/index.html'),
  // replace module higlass import with UMD scripts
  esmHTML.replace(
    /<!-- HIGLASS IMPORT -->(.|\n)*<!-- HIGLASS IMPORT -->/,
    `\
    <link rel="stylesheet" href="./hglib.css">
    <script src="${base}/react@${reactVersion}/umd/react.production.min.js"></script>
    <script src="${base}/react-dom@${reactVersion}/umd/react-dom.production.min.js"></script>
    <script src="${base}/pixi.js@${pixiVersion}/dist/browser/pixi.min.js"></script>
    <script src="./hglib.min.js"></script>
  `,
  ),
);
